name: Build borgbackup

on:
  push:

jobs:
  docker_build_and_publish_github:
    env:
      CONTAINER_NAME: borgbackup
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Get the most recent release version from nextcloud-server and use it as tag for the image
      - uses: actions/github-script@v4
        id: 'latest-tag'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const releases = await github.repos.listReleases({
              owner: 'nextcloud',
              repo: 'server',
            });
            return releases.data[0].tag_name;

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/aio-${{ env.CONTAINER_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.latest-tag.outputs.result }}

      - name: Build docker image and push to github packages
        uses: docker/build-push-action@v2
        with:
          context: ./Containers/${{ env.CONTAINER_NAME }}
          platforms: linux/amd64,linux/arm64
          no-cache: true
          push: true
          build-args: |
            "BRANCH=${{ steps.latest-tag.outputs.result }}"
          tags: ${{ steps.metadata.outputs.tags }}
